name: Deploy new version

# Only deploy when a new tag is pushed
on:
    push:
        tags:
          - "v*.*.*"

    
# Allow this workflow to write back to the repository
permissions:
    contents: write
    
# Build binary and send to releases
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        name: Build and deploy
        steps:
        
          - name: Check out this repository
            uses: actions/checkout@v4
            
          - name: Build Docker image
            run: docker build -t pico-builder-image .
            
          - name: Create Docker container
            run: docker create --name pico-builder-container pico-builder-image
            
          - name: Copy out .uf2 file
            run: docker cp pico-builder-container:/workspace/firmware ./firmware

          - name: Push to release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
                files: ./firmware/*.uf2
                body_path: CHANGELOG.md