name: Handle Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create branch based on issue
      run: |
        ISSUE_TYPE=$(jq --raw-output .issue.labels[0].name "$GITHUB_EVENT_PATH")
        ISSUE_NUMBER=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
        BRANCH_NAME=""
        
        if [[ "$ISSUE_TYPE" == "bug" ]]; then
          BRANCH_NAME="bugfix/issue-$ISSUE_NUMBER"
        elif [[ "$ISSUE_TYPE" == "feature" ]]; then
          BRANCH_NAME="feature/issue-$ISSUE_NUMBER"
        else
          echo "No matching label for new branch. Exiting."
          exit 0
        fi

        echo "Creating new branch: $BRANCH_NAME"
        git checkout -b $BRANCH_NAME
        git push origin $BRANCH_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
